'use strict';
// Obsidian supplies a require function rooted at the application, not at the
// plugin directory. Inline the only local module; keep vendor/Node APIs external.
const fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'main.source.cjs'),'utf8');
const core=fs.readFileSync(path.join(__dirname,'core.cjs'),'utf8');
const marker="const core=require('./core.cjs');";
if(source.split(marker).length!==2)throw Error('Expected exactly one core module import.');
const bundle=source.replace(marker,`const core=(()=>{const module={exports:{}};\n${core}\nreturn module.exports;})();`);
if(/require\(['"]\.\.?\//.test(bundle))throw Error('Bundle contains a local require.');
fs.writeFileSync(path.join(__dirname,'main.js'),'// Generated by build.cjs. Edit main.source.cjs and core.cjs.\n'+bundle);
console.log('Built self-contained main.js');
