// Generated by build.cjs. Edit main.source.cjs and core.cjs.
'use strict';
const {Plugin,ItemView,PluginSettingTab,Setting,Notice,FuzzySuggestModal,Modal,MarkdownRenderer,Component,TFile,parseYaml,requestUrl}=require('obsidian');
const path=require('node:path');
const fs=require('node:fs/promises');
const core=(()=>{const module={exports:{}};
'use strict';
const fs = require('node:fs/promises');
const path = require('node:path');
const { URL } = require('node:url');
const { createHash } = require('node:crypto');
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const execute = promisify(execFile);
const CATEGORIES = ['embodied-ai', 'power-electronics', 'personal'];
const ASSET_EXTENSIONS = new Set(['png','jpg','jpeg','webp','gif','svg','pdf','mp4','mp3','wav']);
const hash = value => createHash('sha256').update(value).digest('hex');
const stripFrontmatter = text => text.replace(/^\uFEFF?---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, '');
const today = () => new Intl.DateTimeFormat('en-CA', {timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function dateValid(value) { const date=new Date(value+'T00:00:00Z');return /^\d{4}-\d{2}-\d{2}$/.test(value) && Number.isFinite(date.valueOf()) && date.toISOString().slice(0,10)===value; }
async function replaceAsync(text, pattern, replace) {
  let result='', start=0;
  for(const match of text.matchAll(pattern)){result+=text.slice(start,match.index)+await replace(...match);start=match.index+match[0].length;}
  return result+text.slice(start);
}
function protectedMarkdown(text) {
  const saved=[];const token=value=>`\uE000${saved.push(value)-1}\uE001`;
  const lines=text.split('\n');let fence=null, block=[], output=[];
  for(const line of lines){
    if(fence){block.push(line);const end=line.match(/^ {0,3}(`{3,}|~{3,})\s*$/);if(end&&end[1][0]===fence[0]&&end[1].length>=fence.length){output.push(token(block.join('\n')));block=[];fence=null;}}
    else {const start=line.match(/^ {0,3}(`{3,}|~{3,})/);if(start){fence=start[1];block=[line];}else output.push(line);}
  }
  if(block.length)output.push(token(block.join('\n')));
  const masked=output.join('\n').replace(/(`+)[^`\n]*?\1/g,m=>token(m));
  return {masked,restore:value=>value.replace(/\uE000(\d+)\uE001/g,(_,i)=>saved[Number(i)])};
}
function suggestSlug(title,identity=title){
  const words=path.posix.basename(String(title||'').replace(/\\/g,'/')).replace(/\.md$/i,'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60).replace(/-+$/,'');
  return words||'post-'+hash(String(identity||title||'article')).slice(0,8);
}
function validateMetadata(meta){
  const title=String(meta.title||'').trim(), description=String(meta.description||'').trim();
  if(!title||!description)throw Error('请填写文章标题和摘要。');
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(meta.slug||'') || meta.slug.length>80)throw Error('网页标识使用小写英文、数字和短横线，例如 my-first-post；不用填写文件路径。可点击“自动生成”。');
  if(!CATEGORIES.includes(meta.category))throw Error('请选择有效的文章分类。');
  if(!dateValid(meta.pubDate)||meta.pubDate>today())throw Error('发布日期必须是有效日期，不能晚于今天。');
  if(meta.updatedDate&&(!dateValid(meta.updatedDate)||meta.updatedDate<meta.pubDate||meta.updatedDate>today()))throw Error('修订日期必须介于发布日期与今天之间。');
  return {...meta,title,description};
}
async function prepareArticle({text,meta,notePath,resolveFile,resolvePublished,resolvePublicAsset,plainLinks=false}) {
  meta=validateMetadata(meta);const {title,description}=meta;
  const assets=new Map(), warnings=[], notices=[];
  const base=`/images/posts/${meta.slug}/`;
  const external=target=>/^(https?:|mailto:|tel:|#)/i.test(target);
  async function asset(reference,embedded,label,original) {
    const file=await resolveFile(reference,notePath);
    if(!file){warnings.push('找不到附件：'+reference);return original;}
    const extension=path.extname(file.path).slice(1).toLowerCase();
    if(!ASSET_EXTENSIONS.has(extension)){warnings.push('不支持嵌入此文件，请改为公开链接：'+reference);return original;}
    const data=Buffer.from(await file.read());
    if(data.byteLength>20*1024*1024)throw Error('附件超过 20 MB：'+reference);
    const name=hash(data).slice(0,16)+'.'+extension;
    const publicPath=base+name;
    assets.set(publicPath,{filePath:`public${publicPath}`,url:publicPath,source:file.path,data,resourceURL:file.resourceURL});
    const alt=String(label||path.basename(file.path)).replace(/[\[\]\n]/g,'');
    return `${embedded&&['png','jpg','jpeg','webp','gif','svg'].includes(extension)?'!':''}[${alt}](${publicPath})`;
  }
  async function link(reference,label,original) {
    if(external(reference))return `[${label}](${reference})`;
    const destination=await resolveFile(reference.split('#')[0],notePath);
    if(destination&&path.extname(destination.path).toLowerCase()!=='.md')return asset(reference,false,label,original);
    const published=destination&&await resolvePublished(destination.path);
    if(published){const anchor=reference.includes('#')?'#'+encodeURIComponent(reference.split('#').slice(1).join('#').toLowerCase().replace(/\s+/g,'-')):'';return `[${label}](/blog/${published.slug}/${anchor})`;}
    if(plainLinks){notices.push('未公开链接已转为文字：'+reference);return label;}
    warnings.push('内部链接尚未公开：'+reference);return original;
  }
  let body=stripFrontmatter(text).trim();
  const first=body.match(/^#\s+(.+)\r?\n/);
  if(first&&(first[1].trim()===title||first[1].trim()===path.basename(notePath,'.md')))body=body.slice(first[0].length).trim();
  const protectedText=protectedMarkdown(body);
  body=protectedText.masked.replace(/%%[\s\S]*?%%/g,'').replace(/<!--[\s\S]*?-->/g,'');
  body=await replaceAsync(body,/(!?)\[\[([^\]\n]+)\]\]/g,async(original,embed,inside)=>{
    const [reference,...alias]=inside.split('|');const target=reference.trim();const label=alias.join('|')||target.split('/').pop().replace(/\.md$/i,'');
    if(embed)return asset(target,true,/^\d+(x\d+)?$/.test(label)?'':label,original);
    return link(target,label,original);
  });
  body=await replaceAsync(body,/(!?)\[([^\]\n]*)\]\((<[^>]+>|[^)\s]+)(\s+(?:"[^"]*"|'[^']*'))?\)/g,async(original,embed,label,destination)=>{
    let reference=destination.replace(/^<|>$/g,'');try{reference=decodeURIComponent(reference);}catch{}
    if(external(reference))return original;
    if(reference.startsWith('/images/posts/')){
      if(!/^\/images\/posts\/[a-z0-9-]+\/[a-f0-9]{16}\.[a-z0-9]+$/.test(reference)){warnings.push('无效的公开附件路径：'+reference);return original;}
      if(assets.has(reference))return original;
      if(resolvePublicAsset&&!await resolvePublicAsset(reference))warnings.push('公开附件不存在：'+reference);
      return original;
    }
    if(reference.startsWith('/blog/'))return original;
    if(embed)return asset(reference,true,label,original);
    return link(reference,label,original);
  });
  if(/<(?:img|video|audio|iframe)\b[^>]*\b(?:src|poster)\s*=\s*["'](?!https?:\/\/)[^"']+/i.test(body))warnings.push('HTML 内的本地附件请改用 Markdown 图片或公开 HTTPS 链接。');
  if(/\]\((?:obsidian:|file:|data:|javascript:)/i.test(body))warnings.push('请移除本地文件、Obsidian 或脚本链接。');
  body=protectedText.restore(body).trim();
  if(!body)throw Error('正文为空，请先写好文章。');
  const tags=Array.isArray(meta.tags)?meta.tags:[];
  const header=['---','title: '+JSON.stringify(title),'description: '+JSON.stringify(description),'pubDate: '+meta.pubDate,...(meta.updatedDate?['updatedDate: '+meta.updatedDate]:[]),'category: '+meta.category,'tags: '+JSON.stringify(tags),'publish: true','draft: false','featured: '+Boolean(meta.featured),'---'];
  const markdown=header.join('\n')+'\n\n'+body+'\n';
  const files=[{filePath:`src/content/blog/${meta.slug}.md`,data:Buffer.from(markdown)},...assets.values()];
  const signature=hash(files.map(f=>f.filePath+':'+hash(f.data)).join('\n'));
  return {meta:{...meta,title,description},body,markdown,assets:[...assets.values()],warnings:[...new Set(warnings)],notices:[...new Set(notices)],files,signature};
}
async function run(binary,args,cwd,options={}){
  const timeout=options.timeout??120000,env={...process.env,GIT_TERMINAL_PROMPT:'0',...options.env};
  // Finder-launched macOS apps normally omit Homebrew/Node from PATH.
  env.PATH=[path.dirname(binary),env.PATH,'/opt/homebrew/bin','/usr/local/bin','/usr/bin','/bin','/usr/sbin','/sbin'].filter(Boolean).join(path.delimiter);
  try{const task=execute(binary,args,{cwd,timeout,maxBuffer:2*1024*1024,env});if(options.onOutput)task.child.stderr.on('data',chunk=>{try{options.onOutput(String(chunk));}catch{}});return (await task).stdout.trim();}
  catch(error){
    const redact=text=>String(text).replace(/(https?:\/\/)[^\s/@]+:[^\s/@]+@/g,'$1[redacted]@').replace(/\b(?:gh[pousr]_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+)\b/g,'[redacted]');
    const label=path.basename(binary)+(path.basename(binary).includes('git')?' '+redact(args.filter((arg,i)=>arg!=='-c'&&args[i-1]!=='-c').join(' ')):'');
    const detail=redact(error.stderr||error.stdout||(!error.killed&&error.code!=='ENOENT'?error.message:'')||'').trim().slice(-2500);
    const reason=error.killed?`命令超时（${Math.round(timeout/1000)} 秒）`:error.code==='ENOENT'?'找不到可执行文件':`命令失败（${error.code??error.signal??'未知错误'}）`;
    const failure=Error(`${reason}：${label}${detail?'\n'+detail:''}${error.killed?'\n请检查 GitHub 网络连接或插件的 Git 代理设置。':''}`);failure.code=error.code;failure.killed=error.killed;throw failure;
  }
}
function normalizeProxy(value){
  const proxy=String(value||'').trim();if(!proxy)return '';
  let url;try{url=new URL(proxy);}catch{throw Error('Git 代理格式无效，例如 http://127.0.0.1:7897。');}
  if(!['http:','https:','socks5:','socks5h:'].includes(url.protocol)||!url.hostname||url.username||url.password||url.search||url.hash||!['','/'].includes(url.pathname))throw Error('Git 代理只填写 HTTP/HTTPS/SOCKS5 地址和端口，不包含密码或路径。');
  return proxy;
}
async function gitNetwork(git,args,root,{gitProxy='',networkTimeout=60000,onOutput}={}){
  const proxy=normalizeProxy(gitProxy);
  return run(git,['-c','http.lowSpeedLimit=1','-c','http.lowSpeedTime=20',...(proxy?['-c','http.proxy='+proxy]:[]),...args],root,{timeout:networkTimeout,onOutput});
}
function pushWait(value=600){const seconds=Number(value);if(!Number.isInteger(seconds)||seconds<60||seconds>1800)throw Error('推送等待时间应为 60–1800 秒。');return seconds*1000;}
async function pushedCommit({repo,commit,git='git',requiredRemote,gitProxy=''}){
  if(!/^(?:[a-f0-9]{40}|[a-f0-9]{64})$/.test(commit||''))throw Error('待推送提交无效，请检查仓库。');
  const state=await repoState(repo,git,requiredRemote);
  const remote=await gitNetwork(git,['ls-remote','origin','refs/heads/main'],state.root,{gitProxy});
  const head=remote.match(/^([a-f0-9]{40,64})\s+refs\/heads\/main$/m)?.[1];
  if(!head)throw Error('远程仓库没有 main 分支。');
  if(head===commit)return true;
  await gitNetwork(git,['fetch','origin','main'],state.root,{gitProxy});
  try{await run(git,['merge-base','--is-ancestor',commit,'origin/main'],state.root);return true;}catch(error){if(error.code===1)return false;throw error;}
}
async function pushCommit({repo,commit,git='git',requiredRemote,gitProxy='',pushTimeoutSeconds=600,onProgress=()=>{}}){
  const timeout=pushWait(pushTimeoutSeconds);onProgress('推送到 GitHub');
  try{await gitNetwork(git,['push','--progress','origin','main'],repo,{gitProxy,networkTimeout:timeout,onOutput:chunk=>{
    const lines=chunk.split(/[\r\n]/).filter(line=>/^(?:Writing objects|Enumerating objects|Counting objects|Compressing objects):/.test(line));
    if(lines.length){const line=lines.at(-1).trim();onProgress(line.replace(/^Writing objects:/,'上传对象：').replace(/^Enumerating objects:/,'统计对象：').replace(/^Counting objects:/,'整理对象：').replace(/^Compressing objects:/,'压缩对象：'));}
  }});return {status:'pushed',commit};}
  catch(error){
    onProgress('推送未正常结束，正在核对远程结果');
    try{if(await pushedCommit({repo,commit,git,requiredRemote,gitProxy}))return {status:'pushed',commit,alreadyPushed:true};}catch{}
    return {status:'pending-push',commit,error:error.message};
  }
}
async function checkConnection({repo,git='git',requiredRemote,gitProxy=''}){
  const state=await repoState(repo,git,requiredRemote);
  const result=await gitNetwork(git,['ls-remote','origin','refs/heads/main'],state.root,{gitProxy});
  if(!/^[a-f0-9]{40,64}\s+refs\/heads\/main$/m.test(result))throw Error('GitHub 仓库没有 main 分支。');
  return state;
}
async function repoState(repo,git='git',requiredRemote='https://github.com/aurorasgod/aurorasgod.github.io.git') {
  const root=await fs.realpath(repo);
  if(await run(git,['rev-parse','--show-toplevel'],root)!==root)throw Error('请设置博客 Git 仓库根目录。');
  await fs.access(path.join(root,'src/content/blog'));
  const remote=await run(git,['remote','get-url','origin'],root);
  const equivalent=remote.replace(/^git@github\.com:/,'https://github.com/').replace(/\.git$/,'');
  if(equivalent!==requiredRemote.replace(/\.git$/,''))throw Error('仓库的 origin 与博客目标不一致。');
  const branch=await run(git,['branch','--show-current'],root);
  if(branch!=='main')throw Error('请切换到 main 分支。');
  const staged=await run(git,['diff','--cached','--name-only'],root);
  if(staged)throw Error('仓库有已暂存的其他修改，请先处理，避免一起发布。');
  return {root,remote,branch,head:await run(git,['rev-parse','HEAD'],root),status:await run(git,['status','--porcelain','--untracked-files=all'],root)};
}
async function safeTarget(root,relative) {
  if(!/^(src\/content\/blog\/[a-z0-9-]+\.md|public\/images\/posts\/[a-z0-9-]+\/[a-f0-9]{16}\.[a-z0-9]+)$/.test(relative))throw Error('无效的导出路径。');
  let current=root;
  for(const segment of relative.split('/')){current=path.join(current,segment);try{if((await fs.lstat(current)).isSymbolicLink())throw Error('导出路径不能包含符号链接。');}catch(e){if(e.code!=='ENOENT')throw e;}}
  return path.join(root,relative);
}
async function articleHash(repo,slug){try{return hash(await fs.readFile(await safeTarget(await fs.realpath(repo),`src/content/blog/${slug}.md`)));}catch(e){if(e.code==='ENOENT')return null;throw e;}}
async function publishArticle({repo,plan,git='git',requiredRemote,gitProxy='',pushTimeoutSeconds=600,expectedArticleHash=null,build,onProgress=()=>{},onCommitted=async()=>{}}) {
  pushWait(pushTimeoutSeconds);
  if(plan.warnings.length)throw Error('请先处理预览中的内部链接或附件问题。');
  const state=await repoState(repo,git,requiredRemote);
  if(state.status)throw Error('博客仓库还有未提交的修改，请先在 GitHub Desktop 处理。');
  const gitdir=path.resolve(state.root,await run(git,['rev-parse','--git-dir'],state.root)), lock=path.join(gitdir,'laplace-blog-publisher.lock');
  try{await fs.mkdir(lock);}catch(e){if(e.code==='EEXIST')throw Error('另一项发布正在进行，请稍后再试。');throw e;}
  const backups=[];let committed=false;
  try {
    onProgress('检查远程仓库');await gitNetwork(git,['fetch','origin','main'],state.root,{gitProxy});
    const behind=Number(await run(git,['rev-list','--count','HEAD..origin/main'],state.root)),ahead=Number(await run(git,['rev-list','--count','origin/main..HEAD'],state.root));
    if(behind)throw Error('远程仓库有新提交，请先在 GitHub Desktop 拉取更新。');
    if(ahead)throw Error('仓库有尚未推送的提交，请先在 GitHub Desktop 处理，或使用插件的重试推送。');
    if(await articleHash(state.root,plan.meta.slug)!==expectedArticleHash)throw Error('文章已在预览后被修改，请重新预览。');
    onProgress(plan.operation==='delete'?'移除网页文章':'导出文章与附件');
    for(const file of plan.files){const target=await safeTarget(state.root,file.filePath);let previous=null;try{previous=await fs.readFile(target);}catch(e){if(e.code!=='ENOENT')throw e;}backups.push({target,previous,writtenHash:file.data===null?null:hash(file.data)});await fs.mkdir(path.dirname(target),{recursive:true});if(file.data===null)await fs.unlink(target);else await fs.writeFile(target,file.data);}
    onProgress('检查网站构建');if(build)await build(state.root);
    const paths=plan.files.map(f=>f.filePath);
    // A build hook or external editor must not sneak unrelated changes into this publish.
    const unstaged=await run(git,['diff','--name-only'],state.root);
    const untracked=await run(git,['ls-files','--others','--exclude-standard'],state.root);
    if((unstaged+'\n'+untracked).split('\n').filter(Boolean).some(p=>!paths.includes(p)))throw Error('构建期间仓库出现了其他修改，请检查后重新发布。');
    if(await run(git,['rev-parse','HEAD'],state.root)!==state.head || await run(git,['diff','--cached','--name-only'],state.root))throw Error('构建期间 Git 仓库被其他操作修改，请检查后重新发布。');
    for(const file of plan.files){let current=null;try{current=await fs.readFile(await safeTarget(state.root,file.filePath));}catch(e){if(e.code!=='ENOENT')throw e;}if((current===null?null:hash(current))!==(file.data===null?null:hash(file.data)))throw Error('构建期间发布稿或附件被其他操作修改，请重新预览。');}
    await run(git,['add','--',...paths],state.root);
    if(!(await run(git,['diff','--cached','--name-only'],state.root)))return {status:'unchanged',commit:state.head};
    onProgress('提交文章');await run(git,['commit','-m',`${plan.operation==='delete'?'Delete':'Publish'}: ${plan.meta.title.slice(0,100)}`,'--',...paths],state.root);
    committed=true;const commit=await run(git,['rev-parse','HEAD'],state.root);await onCommitted(commit);
    return await pushCommit({repo:state.root,commit,git,requiredRemote,gitProxy,pushTimeoutSeconds,onProgress});
  } catch(error) {
    if(!committed){const paths=plan.files.map(f=>f.filePath);await run(git,['reset','--',...paths],state.root).catch(()=>{});for(const {target,previous,writtenHash} of backups){let current=null;try{current=await fs.readFile(target);}catch(e){if(e.code!=='ENOENT')throw e;}if((current===null?null:hash(current))!==writtenHash)continue;if(previous===null)await fs.unlink(target).catch(()=>{});else await fs.writeFile(target,previous);}}
    throw error;
  } finally {await fs.rmdir(lock);}
}
async function retryPush({repo,commit,git='git',requiredRemote,gitProxy='',pushTimeoutSeconds=600,onProgress=()=>{}}) {
  if(await pushedCommit({repo,commit,git,requiredRemote,gitProxy}))return {status:'pushed',commit,alreadyPushed:true};
  const state=await repoState(repo,git,requiredRemote);
  if(state.status||state.head!==commit)throw Error('仓库已发生其他修改，请在 GitHub Desktop 处理推送。');
  await gitNetwork(git,['fetch','origin','main'],state.root,{gitProxy});
  if(Number(await run(git,['rev-list','--count','HEAD..origin/main'],state.root)))throw Error('远程已更新，请在 GitHub Desktop 合并后推送。');
  const result=await pushCommit({repo:state.root,commit,git,requiredRemote,gitProxy,pushTimeoutSeconds,onProgress});if(result.status!=='pushed')throw Error(result.error);return result;
}
function parseArticle(markdown,slug,parseYaml){
  const match=markdown.match(/^\uFEFF?---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
  if(!match)throw Error('文章缺少 YAML 属性。');
  const meta=parseYaml(match[1]);if(!meta||typeof meta!=='object'||Array.isArray(meta))throw Error('文章属性格式无效。');
  const date=value=>value instanceof Date?value.toISOString().slice(0,10):String(value||'').slice(0,10);
  return {slug,markdown,hash:hash(markdown),body:stripFrontmatter(markdown).trim(),meta:{title:String(meta.title||slug),description:String(meta.description||''),slug,category:meta.category,tags:Array.isArray(meta.tags)?meta.tags:[],pubDate:date(meta.pubDate),updatedDate:date(meta.updatedDate),featured:!!meta.featured},public:meta.publish===true&&meta.draft!==true};
}
async function readArticle(repo,slug,parseYaml){const root=await fs.realpath(repo),target=await safeTarget(root,`src/content/blog/${slug}.md`);return parseArticle(await fs.readFile(target,'utf8'),slug,parseYaml);}
async function listArticles(repo,parseYaml){
  const root=await fs.realpath(repo),names=await fs.readdir(path.join(root,'src/content/blog')),result=[];
  for(const name of names.filter(n=>/^[a-z0-9]+(?:-[a-z0-9]+)*\.md$/.test(n))){const slug=name.slice(0,-3);try{result.push(await readArticle(root,slug,parseYaml));}catch(error){result.push({slug,error:error.message,meta:{title:slug},public:false});}}
  return result.sort((a,b)=>String(b.meta.pubDate||'').localeCompare(String(a.meta.pubDate||''))||a.slug.localeCompare(b.slug));
}
async function trashDirectory(repo,git='git'){const root=await fs.realpath(repo),gitdir=path.resolve(root,await run(git,['rev-parse','--git-dir'],root));const target=path.join(gitdir,'laplace-blog-trash');await fs.mkdir(target,{recursive:true});if((await fs.lstat(target)).isSymbolicLink())throw Error('恢复目录不能是符号链接。');return target;}
async function listDeleted(repo,git='git'){
  const dir=await trashDirectory(repo,git),items=[];
  for(const name of await fs.readdir(dir)){if(!/^[a-z0-9-]+\.json$/.test(name))continue;try{const file=path.join(dir,name);if((await fs.lstat(file)).isSymbolicLink())continue;const item=JSON.parse(await fs.readFile(file,'utf8'));if(item.commit&&typeof item.markdown==='string')items.push(item);}catch{}}
  return items.sort((a,b)=>b.deletedAt.localeCompare(a.deletedAt));
}
async function deleteArticle({slug,parseYaml,...options}){
  const article=await readArticle(options.repo,slug,parseYaml);
  if(article.hash!==options.expectedArticleHash)throw Error('文章已修改，请刷新列表后再删除。');
  const dir=await trashDirectory(options.repo,options.git),id=`${slug}-${Date.now()}-${article.hash.slice(0,8)}`,backup=path.join(dir,id+'.json');
  const record={id,slug,title:article.meta.title,markdown:article.markdown,deletedAt:new Date().toISOString(),commit:''};
  await fs.writeFile(backup,JSON.stringify(record,null,2),{flag:'wx'});
  const plan={operation:'delete',meta:article.meta,warnings:[],files:[{filePath:`src/content/blog/${slug}.md`,data:null}]};
  const result=await publishArticle({...options,plan,onCommitted:async commit=>{record.commit=commit;await fs.writeFile(backup,JSON.stringify(record,null,2));await options.onCommitted?.(commit);}});
  return {...result,backupId:id};
}
module.exports={CATEGORIES,hash,today,stripFrontmatter,suggestSlug,validateMetadata,prepareArticle,repoState,articleHash,publishArticle,retryPush,run,normalizeProxy,gitNetwork,checkConnection,pushWait,pushedCommit,parseArticle,readArticle,listArticles,listDeleted,deleteArticle,safeTarget};

return module.exports;})();
const VIEW='laplace-blog-publisher';
const NAMES={'embodied-ai':'具身智能','power-electronics':'电力电子','personal':'个人经历'};
const DEFAULT={repoPath:'',gitPath:'/usr/bin/git',nodePath:'/usr/local/bin/node',gitProxy:'',pushTimeoutSeconds:600,siteURL:'https://aurorasgod.github.io',activityAPI:'https://field-notes-research.gptplus6267.chatgpt.site',defaultCategory:'embodied-ai',drafts:{},publications:{},pendingCommit:'',pendingAction:null,lastCommit:'',lastAction:null};
const button=(parent,label,action,primary=false)=>{const el=parent.createEl('button',{text:label,cls:primary?'mod-cta':'',attr:{type:'button'}});el.onclick=()=>Promise.resolve().then(action).catch(error=>{parent.closest('.lp-publisher')?.querySelector('.lp-status')?.setText(error.message);new Notice(error.message,10000);});return el;};
const dateString=value=>value instanceof Date?value.toISOString().slice(0,10):String(value||'').slice(0,10);
class NotePicker extends FuzzySuggestModal {
 constructor(plugin,choose){super(plugin.app);this.choose=choose;this.setPlaceholder('搜索 Markdown 笔记');}
 getItems(){return this.app.vault.getMarkdownFiles().filter(f=>!/^模板\//.test(f.path));}
 getItemText(file){return file.path;}
 onChooseItem(file){Promise.resolve(this.choose(file)).catch(e=>new Notice(e.message));}
}
class Preview extends Modal {
 constructor(view,plan,source=''){super(view.app);this.view=view;this.p=view.p;this.plan=plan;this.source=source;this.renderComponent=new Component();}
 async onOpen(){
  this.modalEl.addClass('lp-preview-modal');this.titleEl.setText('文章预览');this.renderComponent.load();
  const e=this.contentEl,plan=this.plan;e.createEl('h2',{text:plan.meta.title});e.createEl('p',{cls:'lp-muted',text:`${NAMES[plan.meta.category]} · ${plan.meta.pubDate} · /blog/${plan.meta.slug}/`});
  e.createEl('p',{cls:'lp-muted',text:'保存到：'+path.join(this.p.settings.repoPath,plan.files[0].filePath)});
  const actions=e.createDiv({cls:'lp-actions'});button(actions,'返回编辑',()=>this.close());
  const progress=e.createEl('p',{cls:'lp-muted lp-progress',attr:{role:'status','aria-live':'polite'}});this.view.progressElement=progress;
  this.confirmButton=button(actions,'确认发布并推送',async()=>{this.confirmButton.disabled=true;progress.removeClass('lp-warning');progress.setText('正在检查远程仓库…');try{await this.view.publish(plan);this.close();}catch(error){progress.setText(error.message);progress.addClass('lp-warning');this.confirmButton.disabled=!!plan.warnings.length;throw error;}},true);this.confirmButton.disabled=!!plan.warnings.length;
  e.createEl('p',{cls:'lp-muted',text:`新增附件：${plan.assets.length} 个；已有公开附件保留。`});
  for(const asset of plan.assets)e.createEl('p',{cls:'lp-muted',text:`${asset.source} · ${(asset.data.length/1024).toFixed(1)} KB`});
  for(const warning of plan.warnings)e.createEl('p',{cls:'lp-warning',text:warning});
  for(const notice of plan.notices)e.createEl('p',{cls:'lp-muted',text:notice});
  const preview=e.createDiv({cls:'lp-preview markdown-rendered'});let markdown=plan.body;
  for(const asset of plan.assets)if(asset.resourceURL)markdown=markdown.split(asset.url).join(asset.resourceURL);
  markdown=markdown.replace(/(\]\()\/images\/posts\//g,'$1'+this.p.settings.siteURL.replace(/\/$/,'')+'/images/posts/');
  try{await MarkdownRenderer.render(this.app,markdown,preview,this.source,this.renderComponent);}catch(error){this.confirmButton.disabled=true;progress.setText('预览渲染失败：'+error.message);progress.addClass('lp-warning');}
 }
 onClose(){this.view.progressElement=null;this.renderComponent.unload();this.contentEl.empty();}
}
class DeleteDialog extends Modal {
 constructor(view,article){super(view.app);this.view=view;this.article=article;}
 onOpen(){this.titleEl.setText('删除网页文章');const e=this.contentEl;
  e.createEl('p',{text:`将从博客移除「${this.article.meta.title}」。`});e.createEl('p',{cls:'lp-muted',text:`/blog/${this.article.slug}/`});
  e.createEl('p',{text:'原 Obsidian 笔记和图片附件保留。文章副本会存入本地恢复列表；网站重新部署后，原页面地址将不再显示。'});
  const actions=e.createDiv({cls:'lp-actions'});button(actions,'取消',()=>this.close());const remove=button(actions,'删除并更新网站',async()=>{remove.disabled=true;try{await this.view.remove(this.article);this.close();}catch(e){remove.disabled=false;throw e;}});remove.addClass('mod-warning');
 }
}
class PublisherView extends ItemView {
 constructor(leaf,plugin){super(leaf);this.p=plugin;this.plan=null;this.busy=false;this.target=null;this.filter='';this.listMode='articles';this.expectedHash=null;}
 getViewType(){return VIEW;}
 getDisplayText(){return '网站管理';}
 getIcon(){return 'globe';}
 async onOpen(){await this.render();if(this.p.settings.pendingCommit)try{await this.syncPending();}catch(error){this.status?.setText('同步发布状态失败：'+error.message);}}
 async leave(){if(this.busy)throw Error('正在更新网站，请稍后。');if(this.draft)await this.saveDraft(false);}
 draftKey(){return this.target?'@web/'+this.target.slug:this.p.currentNote?.path;}
 async select(file){
  await this.leave();if(!(file instanceof TFile)||file.extension!=='md')throw Error('请选择 Markdown 笔记；PDF 可作为正文中明确引用的附件。');
  this.target=null;this.p.currentNote=file;const cached=this.p.settings.drafts[file.path],published=this.p.settings.publications[file.path],fm=this.app.metadataCache.getFileCache(file)?.frontmatter||{};
  this.draft=cached||{title:fm.title||file.basename,description:fm.description||'',slug:published?.slug||fm.blog_slug||'',category:NAMES[fm.category]?fm.category:this.p.settings.defaultCategory,tags:Array.isArray(fm.tags)?fm.tags.join(', '):'',pubDate:dateString(fm.pubDate)||core.today(),updatedDate:published?core.today():'',featured:false,plainLinks:false,body:core.stripFrontmatter(await this.app.vault.read(file)).trim()};
  if(published){this.draft.pubDate=published.pubDate;this.draft.updatedDate=core.today();}
  // Old drafts sometimes put the Obsidian file path into the ambiguous address field.
  if(!this.draft.slug||/^\/.+\.md$/i.test(this.draft.slug)||/^[A-Za-z]:[\\/].+\.md$/i.test(this.draft.slug))this.draft.slug=core.suggestSlug(this.draft.title,file.path);
  this.plan=null;await this.render();
 }
 async editArticle(slug){
  await this.leave();const article=await core.readArticle(this.p.settings.repoPath,slug,parseYaml);this.target=article;this.p.currentNote=null;
  const saved=this.p.settings.drafts['@web/'+slug];this.draft=saved?.baseHash===article.hash?saved:{...article.meta,tags:article.meta.tags.join(', '),body:article.body,plainLinks:false,updatedDate:core.today(),baseHash:article.hash};this.plan=null;await this.render();
 }
 async restore(article){
  await this.leave();if(await core.articleHash(this.p.settings.repoPath,article.slug))throw Error('此地址已有文章。请在文章列表中打开，避免覆盖。');
  const parsed=core.parseArticle(article.markdown,article.slug,parseYaml);this.p.currentNote=null;this.target={...parsed,hash:null,restoring:true};this.draft={...parsed.meta,tags:parsed.meta.tags.join(', '),body:parsed.body,updatedDate:core.today(),plainLinks:false,baseHash:null};this.plan=null;this.listMode='articles';await this.render();new Notice('恢复稿已打开。预览并发布后，网页才会恢复。');
 }
 invalidate(){this.plan=null;this.updateOutputPath();this.status?.setText('编辑稿已修改，发布时会显示最新预览。');}
 updateOutputPath(){const slug=this.draft?.slug||'';this.outputPath?.setText(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)?'保存到：'+path.join(this.p.settings.repoPath,'src/content/blog',slug+'.md'):'填写有效网页标识后，插件会自动生成仓库中的保存位置。');}
 field(parent,label,key,multiline=false,type='text',description=''){
  const row=new Setting(parent).setName(label);if(description)row.setDesc(description);row.settingEl.addClass('lp-field');if(multiline)row.settingEl.addClass('lp-field-wide');let input;
  const configure=c=>{input=c.inputEl;input.id='lp-'+key;input.setAttribute('aria-label',label);input.setAttribute('spellcheck','false');if(!multiline)input.type=type;c.setValue(String(this.draft[key]||'')).onChange(value=>{this.draft[key]=value;this.invalidate();});};
  if(multiline)row.addTextArea(configure);else row.addText(configure);return input;
 }
 async prepare(){
  if(!this.draft)throw Error('请先选择笔记或文章。');const meta={...this.draft,tags:this.draft.tags.split(/[,，]/).map(s=>s.trim()).filter(Boolean)};
  core.validateMetadata(meta); // Validate user input before constructing any filesystem path.
  const source=this.p.currentNote?.path||`src/content/blog/${meta.slug}.md`,own=this.p.currentNote&&this.p.settings.publications[source];
  const expected=await core.articleHash(this.p.settings.repoPath,meta.slug);
  if(this.target&&expected!==this.target.hash)throw Error('文章已被其他操作修改，请刷新文章列表并重新打开。');
  if(expected&&!this.target&&own?.slug!==meta.slug)throw Error('这个文章地址已存在，请从文章列表中打开编辑。');
  const plan=await core.prepareArticle({text:this.draft.body,meta,notePath:source,plainLinks:this.draft.plainLinks,
   resolveFile:async reference=>{if(!this.p.currentNote)return null;const clean=reference.split('#')[0],destination=this.app.metadataCache.getFirstLinkpathDest(clean,source)||this.app.vault.getAbstractFileByPath(path.posix.normalize(path.posix.join(path.posix.dirname(source),clean)));if(!(destination instanceof TFile))return null;return {path:destination.path,resourceURL:this.app.vault.getResourcePath(destination),read:async()=>Buffer.from(await this.app.vault.readBinary(destination))};},
   resolvePublished:async destination=>{const record=this.p.settings.publications[destination];return record?.state==='pushed'?record:null;},
   resolvePublicAsset:async reference=>{try{await fs.access(await core.safeTarget(await fs.realpath(this.p.settings.repoPath),'public'+reference));return true;}catch{return false;}}
  });this.expectedHash=expected;plan.expectedArticleHash=expected;return plan;
 }
 async saveDraft(notify=true){const key=this.draftKey();if(!key||!this.draft)return;this.p.settings.drafts[key]={...this.draft};await this.p.save();if(notify)new Notice('编辑稿已保存到本地。');}
 async inspect(){const state=await core.repoState(this.p.settings.repoPath,this.p.settings.gitPath);await fs.access(path.join(state.root,'node_modules/astro/bin/astro.mjs'));this.status.setText(`环境可用 · main · ${state.status?'仓库有未提交修改，请先处理':'仓库干净'}`);}
 async connection(){if(this.busy)throw Error('正在更新网站，请稍候。');this.setBusy(true);this.status.setText('正在检查 GitHub 连接…');try{await core.checkConnection(this.options());this.status.setText('GitHub 连接成功 · '+(this.p.settings.gitProxy?'使用插件设置的 Git 代理':'沿用本机 Git 网络配置'));}catch(error){this.status.setText(error.message);throw error;}finally{this.setBusy(false);}}
 async preview(){if(this.busy)throw Error('正在更新网站，请稍候。');this.setBusy(true);this.status.setText('正在生成预览…');try{this.plan=await this.prepare();await this.saveDraft(false);this.status.setText(this.plan.warnings.length?`有 ${this.plan.warnings.length} 项需要处理，请查看预览。`:'预览已生成，在预览窗口中确认发布并推送。');this.previewModal=new Preview(this,this.plan,this.p.currentNote?.path);this.previewModal.open();return this.previewModal;}catch(error){this.plan=null;this.status.setText(error.message);throw error;}finally{this.setBusy(false);}}
 async build(root){await fs.access(path.join(root,'node_modules/astro/bin/astro.mjs'));await core.run(this.p.settings.nodePath,[path.join(root,'node_modules/astro/bin/astro.mjs'),'build'],root,{env:{SITE_URL:this.p.settings.siteURL,BASE_PATH:'/',PUBLIC_ACTIVITY_API:this.p.settings.activityAPI,PATH:path.dirname(this.p.settings.nodePath)+path.delimiter+(process.env.PATH||'')}});}
 options(){return {repo:this.p.settings.repoPath,git:this.p.settings.gitPath,gitProxy:this.p.settings.gitProxy,pushTimeoutSeconds:this.p.settings.pushTimeoutSeconds,build:root=>this.build(root),onProgress:message=>{this.status?.setText(message+'…');this.progressElement?.setText(message+'…');}};}
 setBusy(value){this.busy=value;for(const control of this.contentEl.querySelectorAll('input,textarea,select,button'))control.disabled=value;for(const toggle of this.toggles||[])toggle.setDisabled(value);if(!value&&this.target)this.contentEl.querySelector('#lp-slug')?.setAttribute('disabled','');}
 async record(commit,action){this.p.settings.pendingCommit=commit;this.p.settings.lastCommit=commit;this.p.settings.pendingAction=action;this.p.settings.lastAction=action;if(action.type==='publish'&&action.source)this.p.settings.publications[action.source]={...action.meta,state:'pending-push',commit};await this.p.save();this.refreshPublicationLinks();}
 refreshPublicationLinks(){if(!this.publicationLinks)return;this.publicationLinks.empty();const record=this.p.settings.publications[this.p.currentNote?.path],action=this.p.settings.pendingAction||this.p.settings.lastAction,slug=this.target?.slug||record?.slug||(action?.type==='publish'?action.slug:null);if(slug)button(this.publicationLinks,'查看文章',()=>this.p.openURL(`/blog/${slug}/`));button(this.publicationLinks,'查看部署记录',()=>require('electron').shell.openExternal('https://github.com/aurorasgod/aurorasgod.github.io/actions'));}
 async complete(result,action){
  if(result.status==='pending-push'){this.status?.setText('文章已保存在本地提交中，推送结果尚未确认。可“同步发布状态”或“重试推送”，无需再次发布。\n'+result.error);new Notice(result.error,10000);return;}
  if(result.status==='pushed'){this.p.settings.pendingCommit='';this.p.settings.pendingAction=null;this.p.settings.lastCommit=result.commit;
   if(action.type==='delete'){for(const [key,record] of Object.entries(this.p.settings.publications))if(record.slug===action.slug)delete this.p.settings.publications[key];}
   else for(const record of Object.values(this.p.settings.publications))if(record.commit===result.commit)record.state='pushed';
   this.p.settings.lastAction=action;await this.p.save();this.refreshPublicationLinks();this.status?.setText(result.alreadyPushed?'已确认远程包含此提交，发布状态已同步。点击“检查部署”查看上线结果。':'已推送。GitHub Pages 将自动部署，部署完成后文章才会上线。点击“检查部署”查看结果。');new Notice(result.alreadyPushed?'发布状态已同步。':'网站更新已推送。');
  }else this.status?.setText('内容没有变化，无需提交。');
 }
 async publish(original){
  if(this.busy||!original||original.warnings.length)throw Error('请先处理预览中提示的问题。');this.setBusy(true);
  try{const latest=await this.prepare();if(latest.signature!==original.signature||latest.expectedArticleHash!==original.expectedArticleHash)throw Error('正文、附件或仓库文件已变化，请重新预览。');await this.saveDraft(false);const action={type:'publish',source:this.p.currentNote?.path||null,slug:latest.meta.slug,meta:latest.meta};
   const result=await core.publishArticle({...this.options(),plan:latest,expectedArticleHash:original.expectedArticleHash,onCommitted:commit=>this.record(commit,action)});await this.complete(result,action);
   if(this.target){this.target.hash=await core.articleHash(this.p.settings.repoPath,latest.meta.slug);this.target.restoring=false;this.draft.baseHash=this.target.hash;await this.saveDraft(false);}this.plan=null;await this.refreshList();return result;
  }catch(e){this.status?.setText(e.message);throw e;}finally{this.setBusy(false);}
 }
 async remove(article){
  if(this.busy)throw Error('正在更新网站，请稍后。');this.setBusy(true);const action={type:'delete',slug:article.slug};
  try{const result=await core.deleteArticle({...this.options(),slug:article.slug,parseYaml,expectedArticleHash:article.hash,onCommitted:commit=>this.record(commit,action)});await this.complete(result,action);if(this.target?.slug===article.slug){delete this.p.settings.drafts['@web/'+article.slug];this.target=null;this.draft=null;this.p.currentNote=null;await this.p.save();}await this.render();}
  catch(e){this.status?.setText(e.message);throw e;}finally{this.setBusy(false);}
 }
 async retry(){if(this.busy)throw Error('正在更新网站。');if(!this.p.settings.pendingCommit)throw Error('没有待重试的提交。');this.setBusy(true);try{const action=this.p.settings.pendingAction||{type:'publish'},result=await core.retryPush({...this.options(),commit:this.p.settings.pendingCommit});for(const r of Object.values(this.p.settings.publications))if(r.commit===result.commit)r.state='pushed';await this.complete(result,action);await this.refreshList();}finally{this.setBusy(false);}}
 async syncPending(){if(this.busy)throw Error('正在更新网站，请稍候。');const commit=this.p.settings.pendingCommit;if(!commit){this.status?.setText('没有待同步的推送。可“检查部署”查看上线结果。');return true;}this.setBusy(true);this.status?.setText('正在核对 GitHub 远程提交…');try{const action=this.p.settings.pendingAction||{type:'publish'},pushed=await core.pushedCommit({...this.options(),commit});if(commit!==this.p.settings.pendingCommit)return false;if(pushed){await this.complete({status:'pushed',commit,alreadyPushed:true},action);await this.refreshList();return true;}this.status?.setText('远程尚未包含此提交。文章已保存在本地，请“重试推送”。');return false;}finally{this.setBusy(false);}}
 async deployment(){if(this.p.settings.pendingCommit&&!(await this.syncPending()))return;const commit=this.p.settings.lastCommit;if(!commit)throw Error('暂无本插件的部署记录。');this.status.setText('正在查询 GitHub Pages 部署…');try{const response=await requestUrl({url:`https://api.github.com/repos/aurorasgod/aurorasgod.github.io/actions/runs?head_sha=${encodeURIComponent(commit)}&per_page=10`,headers:{Accept:'application/vnd.github+json'}});const run=response.json.workflow_runs?.find(r=>r.name==='Publish personal site');this.status.setText(!run?'已推送，尚未找到部署任务。稍后检查，或打开“查看部署记录”。':run.status==='completed'?(run.conclusion==='success'?(this.p.settings.lastAction?.type==='delete'?'删除已部署，文章已下线。已打开的网页请刷新。':'部署成功，网站已更新。已打开的网页请刷新。'):`已推送，但部署未成功：${run.conclusion}。请打开“查看部署记录”。`):'已推送，GitHub 正在构建并部署。完成后点击“查看文章”，或刷新网页。');}catch(error){this.status.setText('已推送；部署状态查询失败，可打开“查看部署记录”。\n'+error.message);throw error;}}
 async refreshList(){
  if(!this.articleList)return;this.articleList.empty();
  try{const records=this.listMode==='trash'?await core.listDeleted(this.p.settings.repoPath,this.p.settings.gitPath):await core.listArticles(this.p.settings.repoPath,parseYaml);const filtered=records.filter(r=>(r.meta?.title||r.title||r.slug).toLowerCase().includes(this.filter.toLowerCase())||r.slug.includes(this.filter.toLowerCase()));
   this.listCount.setText(`${this.listMode==='trash'?'恢复列表':'文章'} · ${records.length}`);
   if(!filtered.length){this.articleList.createEl('p',{cls:'lp-muted lp-list-empty',text:records.length?'没有匹配的文章。':this.listMode==='trash'?'没有删除记录。':'暂无文章。可从 Obsidian 笔记创建。'});return;}
   for(const article of filtered){const row=this.articleList.createDiv({cls:'lp-article-row'+(this.target?.slug===article.slug?' is-active':'')});const open=button(row,article.meta?.title||article.title,()=>this.listMode==='trash'?this.restore(article):this.editArticle(article.slug));open.addClass('lp-article-title');open.disabled=this.busy||!!article.error;
    row.createEl('small',{cls:'lp-muted',text:article.error||`${this.listMode==='trash'?'已删除 · 可恢复':article.public?'公开':'未公开'} · ${article.meta?.pubDate||article.deletedAt?.slice(0,10)||'未设置日期'}`});
    if(this.listMode==='trash')row.createEl('small',{cls:'lp-muted',text:'点击打开恢复稿'});
   }
  }catch(e){this.listCount.setText('文章');this.articleList.createEl('p',{cls:'lp-muted lp-list-empty',text:'无法读取仓库：'+e.message});}
 }
 async render(){
  const e=this.contentEl;e.empty();e.addClass('lp-publisher');this.toggles=[];this.outputPath=null;
  const toolbar=e.createDiv({cls:'lp-toolbar'});toolbar.createEl('h2',{text:'网站管理'});const tools=toolbar.createDiv({cls:'lp-actions'});
  button(tools,'从笔记新建',()=>new NotePicker(this.p,f=>this.select(f)).open());button(tools,'新建草稿',()=>this.p.createDraft());button(tools,'打开博客',()=>this.p.openURL(''));button(tools,'设置',()=>{this.app.setting.open();this.app.setting.openTabById(this.p.manifest.id);});
  const layout=e.createDiv({cls:'lp-layout'}),sidebar=layout.createDiv({cls:'lp-sidebar'});const tabs=sidebar.createDiv({cls:'lp-list-tabs'});
  for(const [id,label] of [['articles','文章'],['trash','恢复列表']]){const b=button(tabs,label,async()=>{if(this.busy)return;this.listMode=id;for(const el of tabs.querySelectorAll('button'))el.classList.toggle('is-active',el===b);await this.refreshList();});if(id===this.listMode)b.addClass('is-active');}
  const search=sidebar.createEl('input',{cls:'search-input',attr:{type:'search',placeholder:'搜索文章','aria-label':'搜索文章'}});search.value=this.filter;search.oninput=()=>{this.filter=search.value;this.refreshList();};
  const listHeader=sidebar.createDiv({cls:'lp-list-header'});this.listCount=listHeader.createSpan({cls:'lp-muted'});button(listHeader,'刷新',()=>this.refreshList());this.articleList=sidebar.createDiv({cls:'lp-article-list'});
  const editor=layout.createDiv({cls:'lp-editor'});this.status=editor.createEl('p',{cls:'lp-status',text:this.p.settings.pendingCommit?'有本地提交需要核对推送结果，可“同步发布状态”或“重试推送”。':'目标：aurorasgod.github.io',attr:{role:'status','aria-live':'polite'}});this.publicationLinks=editor.createDiv({cls:'lp-actions'});this.refreshPublicationLinks();
  if(this.p.currentNote&&!this.draft)return this.select(this.p.currentNote);
  if(this.draft){
   const head=editor.createDiv({cls:'lp-editor-heading'});head.createEl('h3',{text:this.target?(this.target.restoring?'恢复文章':'编辑文章'):'新建文章'});
   if(this.target&&!this.target.restoring){const actions=head.createDiv({cls:'lp-actions'});button(actions,'查看网页',()=>this.p.openURL(`/blog/${this.target.slug}/`));const remove=button(actions,'删除文章',async()=>{await this.leave();new DeleteDialog(this,await core.readArticle(this.p.settings.repoPath,this.target.slug,parseYaml)).open();});remove.addClass('mod-warning');}
   editor.createEl('p',{cls:'lp-source',text:this.p.currentNote?'来源：'+this.p.currentNote.path:'来源：博客仓库 /blog/'+this.target.slug+'/'});
   const fields=editor.createDiv({cls:'lp-fields'});this.field(fields,'标题','title');const slug=this.field(fields,'网页标识','slug',false,'text','网址中 /blog/ 后面的部分，例如 my-first-post。不用填写笔记或仓库路径。');if(this.target)slug.disabled=true;else button(slug.parentElement,'自动生成',()=>{this.draft.slug=core.suggestSlug(this.draft.title,this.p.currentNote?.path);slug.value=this.draft.slug;this.invalidate();});
   this.outputPath=fields.createEl('p',{cls:'lp-muted lp-output-path'});this.updateOutputPath();this.field(fields,'摘要','description',true);
   new Setting(fields).setName('分类').addDropdown(input=>{input.selectEl.id='lp-category';input.selectEl.setAttribute('aria-label','分类');for(const [id,name] of Object.entries(NAMES))input.addOption(id,name);input.setValue(this.draft.category).onChange(value=>{this.draft.category=value;this.invalidate();});});
   this.field(fields,'标签（逗号分隔）','tags');this.field(fields,'发布日期','pubDate',false,'date');this.field(fields,'修订日期','updatedDate',false,'date');
   for(const [key,label] of [['featured','首页置顶'],['plainLinks','未公开笔记链接转为纯文字']])new Setting(fields).setName(label).addToggle(input=>{this.toggles.push(input);input.setValue(!!this.draft[key]).onChange(value=>{this.draft[key]=value;this.invalidate();});});
   const body=this.field(editor,'正文','body',true);body.addClass('lp-body-editor');
   const actions=editor.createDiv({cls:'lp-actions'});button(actions,'保存编辑稿',()=>this.saveDraft());button(actions,'预览',()=>this.preview());button(actions,this.target?'重新读取网页稿':'重新读取原笔记',async()=>{if(this.target){delete this.p.settings.drafts[this.draftKey()];await this.p.save();this.draft=null;await this.editArticle(this.target.slug);}else{this.draft.body=core.stripFrontmatter(await this.app.vault.read(this.p.currentNote)).trim();this.plan=null;await this.render();}});
   const publishRow=editor.createDiv({cls:'lp-actions'});this.publishButton=button(publishRow,this.target?'发布修改':'发布文章',()=>this.preview(),true);publishRow.createSpan({cls:'lp-muted',text:'点击后预览；确认后写入仓库并推送 GitHub。'});
  }else{this.publishButton=null;editor.createEl('h3',{text:'管理博客文章'});editor.createEl('p',{cls:'lp-muted',text:'在左侧选择文章进行修改或删除，或从 Obsidian 笔记创建新文章。'});button(editor,'使用当前笔记',async()=>{if(!this.p.lastNote)throw Error('请先打开一篇 Markdown 笔记。');await this.select(this.p.lastNote);});}
  const footer=editor.createDiv({cls:'lp-actions lp-footer'});button(footer,'检查环境',()=>this.inspect());button(footer,'检查 GitHub 连接',()=>this.connection());button(footer,'同步发布状态',()=>this.syncPending());button(footer,'重试推送',()=>this.retry());button(footer,'检查部署',()=>this.deployment());
  await this.refreshList();
 }
}
class Settings extends PluginSettingTab {
 constructor(app,plugin){super(app,plugin);this.p=plugin;}
 display(){const e=this.containerEl;e.empty();e.createEl('h2',{text:'网站管理'});e.createEl('p',{text:'管理 aurorasgod.github.io 的文章。Git 登录沿用本机配置，删除文章保留本地恢复副本。'});
  for(const [key,name,description] of [['repoPath','博客仓库目录','GitHub 克隆目录的绝对路径。'],['gitPath','Git 路径','macOS 通常为 /usr/bin/git。'],['nodePath','Node.js 路径','发布前用于构建验证。']])new Setting(e).setName(name).setDesc(description).addText(input=>input.setValue(this.p.settings[key]).onChange(async value=>{this.p.settings[key]=value.trim();await this.p.save();}));
  new Setting(e).setName('Git 代理').setDesc('仅用于本插件的 GitHub 连接，不修改系统或 Git 全局设置。留空沿用本机配置，例如 http://127.0.0.1:7897；使用时需保持代理软件运行。').addText(input=>input.setPlaceholder('http://127.0.0.1:7897').setValue(this.p.settings.gitProxy).onChange(async value=>{this.p.settings.gitProxy=value.trim();await this.p.save();}));
  new Setting(e).setName('推送最长等待').setDesc('带 PDF 或图片的首次上传可能较慢，默认 10 分钟。上传停滞时 Git 会提前报错；超时后会核对远程结果。').addDropdown(input=>{for(const minutes of [1,3,5,10,15,30])input.addOption(String(minutes*60),minutes+' 分钟');input.setValue(String(this.p.settings.pushTimeoutSeconds)).onChange(async value=>{this.p.settings.pushTimeoutSeconds=Number(value);await this.p.save();});});
  new Setting(e).setName('默认分类').addDropdown(input=>{for(const [id,name] of Object.entries(NAMES))input.addOption(id,name);input.setValue(this.p.settings.defaultCategory).onChange(async value=>{this.p.settings.defaultCategory=value;await this.p.save();});});
 }
}
class Publisher extends Plugin {
 async onload(){const saved=await this.loadData();this.settings={...DEFAULT,...saved,drafts:saved?.drafts||{},publications:saved?.publications||{}};this.currentNote=null;const active=this.app.workspace.getActiveFile();this.lastNote=active?.extension==='md'?active:null;this.registerView(VIEW,leaf=>new PublisherView(leaf,this));
  this.addRibbonIcon('globe','网站管理',()=>this.open());this.addCommand({id:'open',name:'打开网站管理',callback:()=>this.open()});this.addCommand({id:'publish-current',name:'从当前笔记创建文章',callback:()=>this.open(this.lastNote)});this.addSettingTab(new Settings(this.app,this));
  this.registerEvent(this.app.workspace.on('file-open',file=>{if(file?.extension==='md')this.lastNote=file;}));this.registerEvent(this.app.vault.on('rename',async(file,old)=>{for(const key of ['drafts','publications'])if(this.settings[key][old]){this.settings[key][file.path]=this.settings[key][old];delete this.settings[key][old];}await this.save();}));this.registerObsidianProtocolHandler('laplace-blog',()=>this.open());
 }
 async save(){await this.saveData(this.settings);}
 async open(file){let leaf=this.app.workspace.getLeavesOfType(VIEW)[0];if(!leaf){leaf=this.app.workspace.getLeaf('tab');await leaf.setViewState({type:VIEW,active:true});}await this.app.workspace.revealLeaf(leaf);if(file instanceof TFile&&file.extension==='md')await leaf.view.select(file);return leaf;}
 openURL(relative){require('electron').shell.openExternal(this.settings.siteURL.replace(/\/$/,'')+'/'+relative.replace(/^\//,''));}
 async createDraft(){if(!this.app.vault.getAbstractFileByPath('博客'))await this.app.vault.createFolder('博客');let name='博客/博客草稿.md',i=2;while(this.app.vault.getAbstractFileByPath(name))name=`博客/博客草稿 ${i++}.md`;const file=await this.app.vault.create(name,'---\ntype: blog\ntitle: ""\ndescription: ""\ncategory: '+this.settings.defaultCategory+'\nblog_slug: ""\ntags: []\n---\n\n');await this.app.workspace.getLeaf('tab').openFile(file);await this.open(file);}
 onunload(){this.app.workspace.detachLeavesOfType(VIEW);}
}
module.exports=Publisher;
module.exports._test={PublisherView,Preview,DeleteDialog,DEFAULT,core};
